Models/Stock.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Group20_IoT.Models
{
    public class Stock
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter the Stock Code")]
        [Index(IsUnique = true)]
        [StringLength(255, ErrorMessage = "The Stock Code must not exceed 255 characters")]
        [Display(Name = "Stock Code")]
        public string StockCode { get; set; }

        [Required(ErrorMessage = "Please enter the Stock Name")]
        [StringLength(100,ErrorMessage ="The Stock Name must not exceed 100 characters")]
        [Display(Name = "Stock Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a Description")]
        [StringLength(250, ErrorMessage = "The Description must not exceed 250 characters")]
        public string Description { get; set; }

        [Display(Name="Total Quantity")]
        [Range(0,int.MaxValue,ErrorMessage = "Please enter a valid Total Quantity")]
        public int TotalQuantity { get; set; } = 0;

        [Display(Name = "Quantity on Loan")]
        public int QuantityOnLoan { get; set; } = 0;

        public bool Loanable { get; set; } = true;

        [Range(0.00,double.MaxValue,ErrorMessage ="Please enter a valid Unit Price")]
        [Display(Name = "Unit Price")]
        public decimal UnitPrice { get; set; } = 0;

        [ForeignKey("StorageArea")]
        [Required(ErrorMessage = "Please select a Storage Area")]
        [Display(Name = "Storage Area")]
        public int StorageAreaId { get; set; }

        public StorageArea StorageArea { get; set; }

        [ForeignKey("Users")]
        [Display(Name = "Created By")]
        public int CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; } = DateTime.Now;

        [Display(Name = "Stock Image")]
        public string ImageFile { get; set; }

        public virtual Users Users { get; set; }

        public ICollection<StockDiscrepancy> stockDiscrepancies { get; set; }

        public ICollection<StorageArea> storageAreas { get; set; }

    }
}

Models/ViewModel/StockViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Group20_IoT.Models.ViewModel
{
    public class StockViewModel
    {
        public int? Id { get; set; }
        public string StockCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UnitPrice { get; set; }
        public string Loanable { get; set; }
        public int TotalQuantity { get; set; }  
        public int QuantityOnLoan { get; set; }
        public string Room { get; set; }
        public string StorageArea { get; set; }
        public string Image { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedOn { get;set; }
    }
}

Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Group20_IoT.Models;
using Group20_IoT.Models.ViewModel;
using System.IO;
using Microsoft.IdentityModel.Tokens;

namespace Group20_IoT.Controllers
{
    [SessionChecker("SuperAdmin","Admin")]
    public class StocksController : Controller
    {
        private IoTContext db = new IoTContext();

        public ActionResult Index()
        {
            // Get stock and format room so user knows which room they are assigned to
            var stock =  db.Stock.Include(s => s.StorageArea).Include(s=>s.StorageArea.Room).Include(s=>s.Users).AsEnumerable().OrderBy(s=>s.Name).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode =  s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();

            return View(stock);
        }

        public ActionResult Sort(string sort)
        {
            List<StockViewModel> stock = new List<StockViewModel>();
             if (sort == "StockLow")
            {
                stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s => s.Users).AsEnumerable().OrderBy(s => s.TotalQuantity).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();
            } else if (sort == "StockHigh")
            {
                stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s => s.Users).AsEnumerable().OrderByDescending(s => s.TotalQuantity).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();
            } else if(sort == "OnLoanLow")
            {
                stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s => s.Users).AsEnumerable().OrderBy(s => s.QuantityOnLoan).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();
            } else if (sort == "OnLoanHigh")
            {
                stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s => s.Users).AsEnumerable().OrderByDescending(s => s.QuantityOnLoan).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();
            }
            else
            {
                stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s => s.Users).AsEnumerable().OrderBy(s => s.Name).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();
            }

            return PartialView("_StockTable", stock);
        }

        public ActionResult Search(string searchItem)
        {
            var stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s=>s.Users).AsEnumerable().Where(s => s.StockCode.ToLower().Contains(searchItem.Trim().ToLower())).OrderBy(s => s.Name).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();

            return PartialView("_StockTable", stock);
        }

        public ActionResult Reset()
        {
            var stock = db.Stock.Include(s => s.StorageArea).Include(s => s.StorageArea.Room).Include(s => s.Users).AsEnumerable().OrderBy(s => s.Name).Select(
                s => new StockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    TotalQuantity = s.TotalQuantity,
                    UnitPrice = s.UnitPrice.ToString("C"),
                    QuantityOnLoan = s.QuantityOnLoan,
                    StorageArea = s.StorageArea.Area_Name,
                    Image = s.ImageFile,
                    StockCode = s.StockCode,
                    Loanable = s.Loanable ? "Yes" : "No",
                    Room = $"{s.StorageArea.Room.Room_Number} [{s.StorageArea.Room.Room_Description}]",
                    CreatedBy = s.Users.GetFullName(),
                    CreatedOn = s.CreatedOn.ToString("dd MMMM yyyy")
                }).ToList();
            return PartialView("_StockTable", stock);
        }

        public ActionResult Create()
        {
            // Retrieve distinct roomids for all storage areas (so we know which rooms actually have storage areas)
            var roomWithStorageAreas = db.StorageArea.Where(s => s.Active).Select(s => s.RoomId).Distinct().ToList();
            
            // Only gather details of rooms that have storage areas
            var rooms = db.Room.Where(r => roomWithStorageAreas.Contains(r.Id) && r.Active).OrderBy(r => r.Room_Number).ToList().Select(r => new
            {
                r.Id,
                RoomDetails = $"{r.Room_Number} [{r.Room_Description}]"
            }).ToList();

            if(rooms.Any())
                ViewBag.Rooms = new SelectList(rooms, "Id", "RoomDetails");
            else

Views/Stocks/Create.cshtml
@model Group20_IoT.Models.Stock

@{
    ViewBag.Title = "Create Stock";
}
<style>
    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>

<h2>Create Stock</h2>

<br />

@using (Html.BeginForm("Create", "Stocks", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StockCode, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StockCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StockCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "textarea", id = "descriptionTextArea" } })
            <div id="charCount"></div>
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalQuantity, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalQuantity, new { htmlAttributes = new { @class = "form-control", min = 1, max = int.MaxValue } })
            @Html.ValidationMessageFor(model => model.TotalQuantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            <input type="file" name="image" id="image" accept=".jpg, .jpeg, .png, .gif" />
            @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Loanable, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.Loanable, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Loanable, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StorageArea.RoomId, "Room", htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.DropDownList("Rooms", null, new { id = "ddlRoom" })
            @Html.ValidationMessageFor(model => model.StorageArea.RoomId)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.StorageArea, "Storage Area", htmlAttributes: new { @class = "control-label col-md-2 required-star" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.StorageAreaId, Enumerable.Empty<SelectListItem>(), "Select a Storage Area", new { id = "ddlStorageArea" })
            @Html.ValidationMessageFor(model => model.StorageArea)
        </div>
    </div>
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create Stock" class="btn-primary" />
        </div>
    </div>
</div>
}
<br />
<div>
    @Html.ActionLink("Back to List of Stock", "Index", null, new { @class = "btn-primary" })

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#ddlRoom").change(function () {
                var roomId = $(this).val();
                if (tryParseInt(roomId)) {
                    loadStorageAreas(roomId);
                } else {
                    $("#ddlStorageArea").html("");
                    $("#ddlStorageArea").append(
                        $("<option></option>").val(-1).html("No Storage Areas")
                    );
                }
            });

            // Get the textarea element and character count element
            var textarea = $("textarea[name='Description']");
            var charCount = $("#charCount");

            // Attach an input event listener to the textarea
            // Function to update character count
            function updateCharCount() {
                // Get the current character count
                var currentCount = textarea.val().length;

                // Display the character count
                charCount.text("Character Count: " + currentCount);

                // You can also check if the user exceeds the 250-character limit and provide feedback
                if (currentCount > 250 || currentCount == 0) {
                    charCount.css("color", "red");
                } else {
                    charCount.css("color", "green"); // Reset color
                }
            }

            // Call the updateCharCount function initially
            updateCharCount();

            // Attach an input event listener to the textarea
            textarea.on("input", function () {
                // Call the updateCharCount function when the user types
                updateCharCount();
            });


        function loadStorageAreas(roomId) {
            $.ajax({
                        url: '@Url.Action("GetStorageAreasByRoom", "Stocks")',
                        type: "GET",
                        data: { roomId: roomId },
                        success: function (data) {
                            $("#ddlStorageArea").html("");
                            if (data.length > 0) {
                                $.each(data, function (index, item) {
                                    $("#ddlStorageArea").append(
                                        $("<option></option>").val(item.Value).html(item.Text)
                                    );
                                });
                            } else {
                                $("#ddlStorageArea").append(
                                    $("<option></option>").val(-1).html("No Storage Areas in this Room")
                                );
                            }
                        },
                        error: function () {
                            console.log("Error occurred while loading Stock Areas.");
                }
            });

            }
            $("#ddlRoom").trigger("change");
        });
    </script>
    <script type="text/javascript">
        $("#UnitPrice").on("keypress keyup blur", function (event) {
            // Replace a comma with a period
            if (event.key === ',') {
                $(this).val($(this).val() + '.');
                event.preventDefault(); // Prevent the comma from being added
            }

            // Allow only digits and a single period
            $(this).val($(this).val().replace(/[^0-9\.]/g, ''));

            // Remove extra periods
            if ($(this).val().match(/\./g) && $(this).val().match(/\./g).length > 1) {
                $(this).val($(this).val().replace(/\.$/m, ''));
            }
        });

        $("#TotalQuantity").on("keypress keyup blur", function (event) {
            // Allow only digits and backspace key (code 8)
            if (event.keyCode !== 8 && (event.keyCode < 48 || event.keyCode > 57)) {
                event.preventDefault();
            }
        });
    </script>

}

Views/Stocks/Index.cshtml
@{
    ViewBag.Title = "Stock Management";
}
<style>
    .card {
        width: 100% !important;
        margin-bottom: 1.7rem !important;
        background-color: #2E3842 !important;
        color: #fff !important; /* Change text color to white */
    }

    .card-header {
        background-color: #003366 !important;
        color: #fff !important; /* Change text color to white */
        text-align: center !important;
        padding: 0.75rem !important;
        font-weight: bold !important;
    }

    .card-body {
        padding: 1.25rem !important;
    }

    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>

<h2>Stock Management</h2>
<br />
<p>
    @Html.ActionLink("Create Stock", "Create", null, new { @class = "btn-primary" })
</p>
<br />
<div>
    <label>Enter Stock Code</label>
    <input type="text" id="searchInput" />
    <button id="searchButton" class="btn-primary">Search</button>            
    <br />
    <button id="resetButton" class="btn-primary" style="display:none">Reset</button>
    <br />
    <select id="filterSortby">
        <option value="">Default Sorting</option>
        <option value="StockLow">Sort By Quantity: Low To High</option>
        <option value="StockHigh">Sort By Quantity: High To Low</option>
        <option value="OnLoanLow">Sort By Quantity On Loan: Low To High</option>
        <option value="OnLoanHigh">Sort By Quantity On Loan: High To Low</option>
    </select>
</div>
<br />
<div id="stockTable">
    @Html.Partial("_StockTable", Model as List<Group20_IoT.Models.ViewModel.StockViewModel>)
</div>

@section scripts {
    <script>
        $(document).ready(function () {

            var ResetButton = $("#resetButton");

            $("#searchButton").click(function () {
                var searchItem = $("#searchInput").val();

                $.ajax({
                    url: '@Url.Action("Search", "Stocks")',
                    type: "GET",
                    data: { searchItem: searchItem },
                    success: function (data) {
                        $("#stockTable").html(data);
                        ResetButton.show();
                    },
                    error: function () {
                        notifyError("Error occurred while searching.");
                        ResetButton.show();
                    }
                });
            });

                ResetButton.click(function () {

        $.ajax({
            url: '@Url.Action("Reset", "Stocks")',
            type: "GET",
            success: function (data) {
                $("#stockTable").html(data);
                ResetButton.hide();
            },
            error: function () {
                notifyError("Error occurred while resetting.");
                ResetButton.show();
            }
        });


});

            $("#filterSortby").change(function () {
                var sort = $(this).val();
                    $.ajax({
                    url: '@Url.Action("Sort", "Stocks")',
                    type: "GET",
                        data: { sort: sort },
                    success: function (data) {
                        $("#stockTable").html(data);
                    },
                    error: function () {
                        notifyError("Error occurred while filtering.");
                    }
                });


            });
        });
    </script>
}

Views/Stocks/_StockTable.cshtml
@model List<Group20_IoT.Models.ViewModel.StockViewModel>


<div class="card-header">
</div>
<div class="card-body">
    <div class="row">
        @foreach (var item in Model)
        {
            
                <div class="card">
                    <div style="text-align:center"><img src="~/Content/Images/@item.Image" class="card-img-top" alt="@item.Image" style="max-height: 200px; max-width: 200px;"></div>
                    
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">@item.StockCode</p>
                        <p class="card-text">@item.Description</p>
                        <p class="card-text">@item.UnitPrice</p>
                        <p class="card-text"><strong>Total Quantity:</strong> @item.TotalQuantity</p>
                        <p class="card-text"><strong>Quantity On Loan:</strong> @item.QuantityOnLoan</p>
                        <p class="card-text"><strong>Located at:</strong> @item.Room~@item.StorageArea</p>
                        <p class="card-text"><strong>Available for Loan:</strong> @item.Loanable</p>
                        <p class="card-text"><strong>Created:</strong> @item.CreatedBy on @item.CreatedOn</p>
                        @Html.ActionLink("Edit Stock Details", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            
        }
    </div>
</div>