Controllers/RequestLoanController.cs
using Group20_IoT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;

namespace Group20_IoT.Controllers
{
    [SessionChecker("Member", "Admin")]
    public class RequestLoanController : Controller
    {
        private IoTContext db = new IoTContext();
        public ActionResult Index()
        {
            Users users = Session["User"] as Users;
            return View(db.RequestLoanStock.Include(r => r.Stock).Where(r => r.UserId == users.Id && r.Status != RequestLoanStock.RequestStatus.Accepted).OrderByDescending(r => r.DateRequested).OrderBy( r=> r.Status).ToList());
        }

        public ActionResult Search(int? id)
        {
            Users users = Session["User"] as Users;
            List<RequestLoanStock> requestLoanStocks = new List<RequestLoanStock>();
            if(!id.HasValue)
            {
                requestLoanStocks = db.RequestLoanStock.Include(r => r.Stock).Where(r => r.UserId == users.Id && r.Status != RequestLoanStock.RequestStatus.Accepted).OrderByDescending(r => r.DateRequested).OrderBy(r => r.Status).ToList();
            }
            else
            {
                requestLoanStocks = db.RequestLoanStock.Include(r => r.Stock).Where(r => r.UserId == users.Id && r.Status != RequestLoanStock.RequestStatus.Accepted && r.Id == id).OrderByDescending(r => r.DateRequested).OrderBy(r => r.Status).ToList();
            }

            return PartialView("_RequestLoanTable", requestLoanStocks);
        }

        public ActionResult Reset()
        {
            Users users = Session["User"] as Users;
            List<RequestLoanStock> requestLoanStocks = db.RequestLoanStock.Include(r => r.Stock).Where(r => r.UserId == users.Id && r.Status != RequestLoanStock.RequestStatus.Accepted).OrderByDescending(r => r.DateRequested).OrderBy(r => r.Status).ToList();
            return PartialView("_RequestLoanTable", requestLoanStocks);
        }

        public ActionResult Sort(int? sort)
        {
            Users users = Session["User"] as Users;
            List<RequestLoanStock> requestLoanStocks = new List<RequestLoanStock>();
            if (sort == 0 || sort == 2 || sort == 3)
            {
                requestLoanStocks = db.RequestLoanStock.Include(r => r.Stock).Where(r => r.UserId == users.Id && (int)r.Status == sort).OrderByDescending(r => r.DateRequested).OrderBy(r => r.Status).ToList();
            }else
                requestLoanStocks = db.RequestLoanStock.Include(r => r.Stock).Where(r => r.UserId == users.Id && r.Status != RequestLoanStock.RequestStatus.Accepted).OrderByDescending(r => r.DateRequested).OrderBy(r => r.Status).ToList();
            return PartialView("_RequestLoanTable", requestLoanStocks);
        }

        public ActionResult AcceptedLoans()
        {
            Users users = Session["User"] as Users;

            var AcceptedReq = db.LoanStatus.Include(r => r.RequestLoanStock).Include(r => r.RequestLoanStock.Stock).Where(r => r.RequestLoanStock.UserId == users.Id).OrderByDescending(r => r.AccOn).ToList();

            return View(AcceptedReq);

        }

        [HttpPost]
        public ActionResult RequestExtension(int? id, string reason)
        {
            if (id == null) return RedirectToAction(nameof(AcceptedLoans));

            LoanStatus loanStatus = db.LoanStatus.Find(id);

            if (loanStatus == null) return RedirectToAction(nameof(AcceptedLoans));

            loanStatus.RequestExtension = true;

            ExtensionRequest request = new ExtensionRequest
            {
                LoanStatusId = loanStatus.Id,
                Reason = reason,
                Status = ExtensionRequest.ExtensionStatus.Pending
            };

            db.ExtensionRequest.Add(request);
            db.Entry(loanStatus).State = EntityState.Modified;

            db.SaveChanges();

            Users user = Session["User"] as Users;
            RequestLoanStock reqStock = db.RequestLoanStock.Find(loanStatus.RequestId);
            Stock stock = db.Stock.Find(reqStock.StockId);


            _ = SharedMethods.SendEmail(user.GetFullName(), user.Email, $"IoT System - Extension Request Submitted [Loan Reference #{loanStatus.Id}]", $"Hello, {user.GetFullName()}.\n\nThe extension you requested regarding\n \"{reqStock.Quantity} x {stock.Name}\" \n, has been submitted.\n\nThank you.\nKind regards,\nIoT System.", false);

            return Json(new { success = true, message = "Your request for an Extension has been submitted" });
        }


        [HttpPost]
        public ActionResult CancelRequest(int? id)
        {
            if (id == null) return RedirectToAction(nameof(Index));

            var Request = db.RequestLoanStock.Find(id);

            if (Request == null) return RedirectToAction(nameof(Index));

            Request.Status = RequestLoanStock.RequestStatus.Cancelled;

            db.Entry(Request).State = EntityState.Modified;
            db.SaveChanges();

            return Json(new { success = true, message = "Loan Request has been cancelled" });
        }

        [HttpPost]
        public ActionResult CancelAcceptedRequest(int? id)
        {
            if (id == null) return RedirectToAction(nameof(Index));

            var Request = db.RequestLoanStock.Find(id);

            if (Request == null) return RedirectToAction(nameof(Index));

            Request.Status = RequestLoanStock.RequestStatus.Cancelled;

            Stock stock = db.Stock.Find(Request.StockId);
            stock.QuantityOnLoan -= Request.Quantity;

            db.Entry(stock).State = EntityState.Modified;
            db.Entry(Request).State = EntityState.Modified;
            db.SaveChanges();

            return Json(new { success = true, message = "Loan Request has been cancelled" });
        }
    }
}

Views/RequestLoan/AcceptedLoans.cshtml
@model IEnumerable<Group20_IoT.Models.LoanStatus>
    @using Group20_IoT.Helpers 
@{
    ViewBag.Title = "Accepted Loans";
}
<style>
    .card {
        width: 100% !important;
        margin-bottom: 1.7rem !important;
        background-color: #2E3842 !important;
        color: #fff !important; /* Change text color to white */
    }

    .card-header {
        background-color: #003366 !important;
        color: #fff !important; /* Change text color to white */
        text-align: center !important;
        padding: 0.75rem !important;
        font-weight: bold !important;
    }

    .card-body {
        padding: 1.25rem !important;
    }

    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }

    .cancel-button {
        background-color: #dc3545;
        color: #fff;
        border: none;
        padding: 5px 10px;
        border-radius: 3px;
        cursor: pointer;
    }

        .cancel-button:hover {
            background-color: #c82333;
        }

    /* Add white text color to the table */
    table, th, td {
        color: #fff;
    }
</style>
<div class="card">
    <div class="card-header">
        <h2>Accepted Loans</h2>
    </div>
    <div class="card-body">


        <table class="table">
            <tr>
                <th>
                    Reference #
                </th>
                <th>
                    Stock Code
                </th>
                <th>
                    Stock Name
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Date Requested
                </th>
                <th>
                    Loan Date
                </th>
                <th>
                    Due Date
                </th>
                <th>
                    Loan Status
                </th>
                <th>
                    Requested For an Extension?
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@Html.DisplayFor(modelItem => item.Id)</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@Html.DisplayFor(modelItem => item.RequestLoanStock.Stock.StockCode)</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@Html.DisplayFor(modelItem => item.RequestLoanStock.Stock.Name)</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@Html.DisplayFor(modelItem => item.RequestLoanStock.Quantity)</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@item.RequestLoanStock.DateRequested.ToString("dd MMMM yyyy")</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@item.RequestLoanStock.FromDate.ToString("dd MMMM yyyy")</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@item.RequestLoanStock.DueDate.ToString("dd MMMM yyyy")</td>
                    <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">@Html.DisplayEnumFor(model => item.Status)</td>
                    @if (item.RequestExtension)
                    {
                       <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">Yes</td>
                    }
                    else
                    {
                <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">No</td>
                    }
                    @if (item.Status == Group20_IoT.Models.LoanStatus.LoanStatusStock.Picked_Up || item.Status == Group20_IoT.Models.LoanStatus.LoanStatusStock.Overdue)
                    {
                        <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">
                            <button id="requestButton" data-target="#RequestModal-@item.Id" data-toggle="modal" class="btn btn-primary">Request An Extension</button>
                            <div class="modal fade" data-keyboard="false" data-backdrop="static" id="RequestModal-@item.Id" tabindex="-1">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content" style="background-color: #2E3842; color: #fff;">
                                        <div class="modal-header">
                                            <input type="button" value="&#x274C;" class="close" data-dismiss="modal" />
                                            <p class="modal-title" style="color:white">Request An Extension</p>
                                        </div>
                                        <div class="modal-body">
                                            <form id="extensionRequestForm">
                                                <div class="form-group">
                                                    <label for="extensionReason">Reason for Extension:</label>
                                                    <textarea class="form-control" id="extensionReason" rows="4" required></textarea>
                                                </div>
                                                <p>P.S. If your extension request is accepted, your Due Date for this loan will be pushed by 3 working days.</p>
                                                <p>An email will be sent to you if your extension is accepted or rejected.</p>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button id="confirmExtensionRequest" class="btn btn-primary" onclick="ExtensionRequest(@item.Id)" data-dismiss="modal">Request Extension</button>&nbsp;&nbsp;
                                            <button class="btn-primary id="Close-@item.Id" data-dismiss="modal">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    }
                    @if (item.Status == Group20_IoT.Models.LoanStatus.LoanStatusStock.Awaiting_Pickup)
                    {
                        <td style="background-color: #2E3842; color: #fff; padding: 0.75rem;">
                            <button class="cancel-button" data-id="@item.Id">Cancel</button>
                        </td>
                    }
                </tr>
            }

        </table>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {

            $(".cancel-button").on("click", function () {
            var ID = $(this).data("id");
                cancelLoan(ID);
        });

        function cancelLoan(ID) {
            $.ajax({
                url: '@Url.Action("CancelAcceptedRequest", "RequestLoan")',
                type: 'POST',
                data: { id: ID },
                dataType: 'json',
                success: function (data) {
                    localStorage.setItem('notificationMessage', data.message);
                    location.reload();
                },
                error: function () {
                    notifyError("An error occurred while cancelling the request.");

                }
            });
        }
    });
    </script>

    <script>
        function ExtensionRequest(id)
        {
            var extensionReason = document.getElementById("extensionReason").value;

            if (extensionReason.trim() === "")
            {
                notifyError("Please enter a reason for the extension.");
                return;
            }

        $.ajax({
    url: '@Url.Action("RequestExtension", "RequestLoan")',
    type: 'POST',
            data: { id: id, reason: extensionReason },
    dataType: 'json',
    success: function (data) {
        localStorage.setItem('notificationMessage', data.message);
        location.reload();
    },
    error: function () {
        notifyError("An error occurred while creating a request for an extension.");

    }
});
        }
    </script>


}

Views/RequestLoan/Index.cshtml
@model IEnumerable<Group20_IoT.Models.RequestLoanStock>
@{
    ViewBag.Title = "My Loan Requests";
}
<style>
    .card {
        width: 100% !important;
        margin-bottom: 1.7rem !important;
        background-color: #2E3842 !important;
        color: #fff !important; /* Change text color to white */
    }

    .card-header {
        background-color: #003366 !important;
        color: #fff !important; /* Change text color to white */
        text-align: center !important;
        padding: 0.75rem !important;
        font-weight: bold !important;
    }

    .card-body {
        padding: 1.25rem !important;
    }

    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>
<div class="card">
    <div class="card-header">
        <h2>My Loan Requests</h2>
    </div>
    <div class="card-body">
        @Html.ActionLink("My Accepted Loan Requests", "AcceptedLoans", null, new { @class = "btn btn-primary" })

        <div>
            <label>Enter Reference #</label>
            <input type="number" id="searchInput" min="0" max="@int.MaxValue" />
            <button id="searchButton" class="btn-primary">Search</button>
            <br />
            <button id="resetButton" class="btn-primary" style="display:none">Reset</button>
            <br />
            <select id="filterSortby">
                <option value="">Default Filter</option>
                <option value=0>Filter Pending</option>
                <option value=2>Filter Rejected</option>
                <option value=3>Filter Cancelled</option>
            </select>
        </div>
        <br />
        <div id="requestLoanTable">
            @Html.Partial("_RequestLoanTable", Model as IEnumerable<Group20_IoT.Models.RequestLoanStock>)
        </div>

    </div>
</div>


@section scripts
{
    <script>
        $(document).ready(function () {

             var ResetButton = $("#resetButton");

 $("#searchButton").click(function () {
     var searchItem = $("#searchInput").val();

     $.ajax({
         url: '@Url.Action("Search", "RequestLoan")',
         type: "GET",
         data: { id: searchItem },
         success: function (data) {
             $("#requestLoanTable").html(data);
             ResetButton.show();
         },
         error: function () {
             notifyError("Error occurred while searching.");
             ResetButton.show();
         }
     });
 });
            ResetButton.click(function () {

                $.ajax({
                    url: '@Url.Action("Reset", "RequestLoan")',
                    type: "GET",
                    success: function (data) {
                        $("#requestLoanTable").html(data);
                        ResetButton.hide();
                    },
                    error: function () {
                        notifyError("Error occurred while resetting.");
                        ResetButton.show();
                    }
                });
            });

             $("#filterSortby").change(function () {
     var sort = $(this).val();
         $.ajax({
         url: '@Url.Action("Sort", "RequestLoan")',
         type: "GET",
             data: { sort: sort },
         success: function (data) {
             $("#requestLoanTable").html(data);
         },
         error: function () {
             notifyError("Error occurred while filtering.");
         }
     });


 });
 });


    </script>

    <script>

            $(".cancel-button").on("click", function () {
            var ID = $(this).data("id");
                cancelLoan(ID, false);
        });

        function cancelLoan(ID) {
            $.ajax({
                url: '@Url.Action("CancelRequest", "RequestLoan")',
                type: 'POST',
                data: { id: ID },
                dataType: 'json',
                success: function (data) {
                localStorage.setItem('notificationMessage', data.message);
                location.reload();
                },
                error: function () {
                notifyError("An error occurred while cancelling the request.");

                }
                });
                }
    </script>


}

Views/RequestLoan/_RequestLoanTable.cshtml
@model IEnumerable<Group20_IoT.Models.RequestLoanStock>


<table class="table text-white">
    <thead>
        <tr>
            <th>
                Reference #
            </th>
            <th>
                Stock
            </th>
            <th>
                Quantity
            </th>
            <th>
                Date Requested
            </th>
            <th>
                Loan Date
            </th>
            <th>
                Due Date
            </th>
            <th>
                Status
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock.Name) [@Html.DisplayFor(modelItem => item.Stock.StockCode)]
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @item.DateRequested.ToString("dd MMMM yyyy")
                </td>
                <td>
                    @item.FromDate.ToString("dd MMMM yyyy")
                </td>
                <td>
                    @item.DueDate.ToString("dd MMMM yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                @if (item.Status == Group20_IoT.Models.RequestLoanStock.RequestStatus.Pending)
                {
                    <td>
                        <button class="btn btn-danger cancel-button" data-id="@item.Id">Cancel</button>
                    </td>
                }
                <td>
                </td>
            </tr>
        }
    </tbody>
</table>