Models/ViewModel/LoanStockViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Group20_IoT.Models.ViewModel
{
    public class LoanStockViewModel
    {
        public int Id { get; set; }

        public string StockCode { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string ImageFile { get; set; }

        public int QuantityCanLoan { get; set; }
    }
}

Controllers/LoanStockController.cs
using Group20_IoT.Models;
using Group20_IoT.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Group20_IoT.Controllers
{
    [SessionChecker("Member", "Admin")]
    public class LoanStockController : Controller
    {
        private IoTContext db = new IoTContext();
        // GET: LoanStock
        public ActionResult Index()
        {
            var LoanableStock = db.Stock.Where(s => s.Loanable).Select(s => new LoanStockViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Description = s.Description,
                ImageFile = s.ImageFile,
                StockCode = s.StockCode,
                QuantityCanLoan = ((s.TotalQuantity - s.QuantityOnLoan) <= 0) ? 0 : s.TotalQuantity - s.QuantityOnLoan
            }).ToList();    

            return View(LoanableStock);
        }

        public ActionResult Search(string searchItem)
        {
            List<LoanStockViewModel> LoanableStock = new List<LoanStockViewModel>();
            if (string.IsNullOrEmpty(searchItem))
            {
                LoanableStock = db.Stock.Where(s => s.Loanable).Select(s => new LoanStockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    ImageFile = s.ImageFile,
                    StockCode = s.StockCode,
                    QuantityCanLoan = ((s.TotalQuantity - s.QuantityOnLoan) <= 0) ? 0 : s.TotalQuantity - s.QuantityOnLoan
                }).ToList();
            }
            else
            {
                LoanableStock = db.Stock.Where(s => s.Loanable && s.Name.ToLower().Contains(searchItem.Trim().ToLower())).Select(s => new LoanStockViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Description = s.Description,
                    ImageFile = s.ImageFile,
                    StockCode = s.StockCode,
                    QuantityCanLoan = ((s.TotalQuantity - s.QuantityOnLoan) <= 0) ? 0 : s.TotalQuantity - s.QuantityOnLoan
                }).ToList();
            }
            return PartialView("_LoanStockTable", LoanableStock);
        }

        public ActionResult Reset()
        {
            var LoanableStock = db.Stock.Where(s => s.Loanable).Select(s => new LoanStockViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Description = s.Description,
                ImageFile = s.ImageFile,
                StockCode = s.StockCode,
                QuantityCanLoan = ((s.TotalQuantity - s.QuantityOnLoan) <= 0) ? 0 : s.TotalQuantity - s.QuantityOnLoan
            }).ToList();
            return PartialView("_LoanStockTable", LoanableStock);
        }

        public ActionResult Filter(string sort)
        {
            List<LoanStockViewModel> LoanableStock =  db.Stock.Where(s => s.Loanable).Select(s => new LoanStockViewModel
            {
                Id = s.Id,
                Name = s.Name,
                Description = s.Description,
                ImageFile = s.ImageFile,
                StockCode = s.StockCode,
                QuantityCanLoan = ((s.TotalQuantity - s.QuantityOnLoan) <= 0) ? 0 : s.TotalQuantity - s.QuantityOnLoan
            }).ToList();
            if (sort == "StockLow")
                LoanableStock.OrderBy(l => l.QuantityCanLoan);
            else if (sort == "StockHigh")
                LoanableStock.OrderByDescending(l => l.QuantityCanLoan);

            return PartialView("_LoanStockTable", LoanableStock);
        }

        public ActionResult Details(int? id)
        {
            if(id == null) return RedirectToAction("Index");

            Stock stock = db.Stock.Find(id);

            if (stock == null) return RedirectToAction("Index");

            LoanStockDetailsViewModel obj = new LoanStockDetailsViewModel
            {
                StockId = stock.Id,
                StockCode = stock.StockCode,
                Name = stock.Name,
                Description = stock.Description,
                QuantityAva = ((stock.TotalQuantity - stock.QuantityOnLoan) <= 0) ? 0 : (stock.TotalQuantity - stock.QuantityOnLoan),
                QuantityWantToLoan = 1,
                Image = stock.ImageFile
            };

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(LoanStockDetailsViewModel obj)
        {
            if(ModelState.IsValid)
            {
                Users users = Session["User"] as Users;
                if (obj.QuantityWantToLoan > obj.QuantityAva)
                {
                    ModelState.AddModelError("QuantityWantToLoan", "This quantity exceeds the Quantity Available to loan.");
                    return View(obj);
                }

                RequestLoanStock requestLoanStock = new RequestLoanStock
                {
                    StockId=obj.StockId,
                    FromDate = obj.BorrowStartDate,
                    DueDate = SharedMethods.AddBusinessDays(obj.BorrowStartDate,7),
                    Quantity = obj.QuantityWantToLoan,
                    UserId = users.Id
                };

                Stock stock = db.Stock.Find(obj.StockId);
                
                _ = SharedMethods.SendEmail(users.GetFullName(), users.Email, "IoT System - Loan Stock Request Submitted", $"Hello, {users.GetFullName()}.\n\nYour request to loan\n \"{obj.QuantityWantToLoan} x {stock.Name}\" \nhas been submitted.\nYou will receive an email when your loan request has been accepted/rejected.\n\nThank you.\nKind regards,\nIoT System.", false);

                db.RequestLoanStock.Add(requestLoanStock);
                db.SaveChanges();
                return RedirectToAction("Index", "RequestLoan");
            }

            return View(obj);
        }
    }
}

Views/LoanStock/Details.cshtml
@model Group20_IoT.Models.ViewModel.LoanStockDetailsViewModel
@{
    ViewBag.Title = "Stock Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .card {
        width: 100% !important;
        margin-bottom: 1.7rem !important;
        background-color: #2E3842 !important;
        color: #fff !important; /* Change text color to white */
    }

    .card-header {
        background-color: #003366 !important;
        color: #fff !important; /* Change text color to white */
        text-align: center !important;
        padding: 0.75rem !important;
        font-weight: bold !important;
    }

    .card-body {
        padding: 1.25rem !important;
    }

    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>

<div class="card">
    <div class="card-header">
        <h2 class="mb-0">Stock Details</h2>
    </div>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.StockId)
            @Html.HiddenFor(m => m.Image)

            <div class="form-group">
                <label for="StockCode">Stock Code:</label>
                <div class="input-group">
                    @Html.EditorFor(model => model.StockCode, new { htmlAttributes = new { @class = "form-control readonly", @readonly = true } })
                </div>
            </div>

            <div class="form-group">
                <label for="Name">Stock Name:</label>
                <div class="input-group">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control readonly", @readonly = true } })
                </div>
            </div>

            <div class="form-group">
                <label for="Description">Description:</label>
                <div class="input-group">
                    @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "textarea" }, @readonly = true })
                </div>
            </div>

            <div class="form-group">
                <label for="QuantityAva">Quantity Available:</label>
                <div class="input-group">
                    @Html.EditorFor(model => model.QuantityAva, new { htmlAttributes = new { @class = "form-control readonly", @readonly = true } })
                </div>
            </div>

            <div class="form-group">
                <label for="Image">Image:</label>
                <div class="input-group">
                    <img src="~/Content/Images/@Model.Image" alt="@Model.Image" class="img-thumbnail" style="max-height:100px;max-width:100px" />
                </div>
            </div>

            <div class="form-group">
                <label for="QuantityWantToLoan" class="required-star">Quantity You Want To Loan:</label>
                <div class="input-group">
                    @Html.EditorFor(model => model.QuantityWantToLoan, new { htmlAttributes = new { @class = "form-control", min = 1, max = Model.QuantityAva } })
                </div>
            </div>

            <div class="form-group">
                <label for="BorrowStartDate" class="required-star">Borrow Date:</label>
                <div class="input-group">
                    @Html.EditorFor(model => model.BorrowStartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Loan" class="btn btn-primary" />
            </div>
            <br />
            <div>
                @Html.ActionLink("Back to List of Stock", "Index", null, new { @class = "btn-primary" })
            </div>
        }
    </div>
</div>


@section Scripts
{
    <script>

        // Get the current date
        var currentDate = new Date();

        // Function to check if a date is a weekday (Monday to Friday)
        function isWeekday(date) {
            var day = date.getDay();
            return day >= 1 && day <= 5; // Monday to Friday
        }

        // Function to calculate the next weekday from a given date
        function getNextWeekday(date) {
            var nextDay = new Date(date);
            nextDay.setDate(date.getDate() + 1); // Start with the next day
            while (!isWeekday(nextDay)) {
                nextDay.setDate(nextDay.getDate() + 1);
            }
            return nextDay;
        }

        $(".datepicker").datepicker({
            dateFormat: 'yy/mm/dd',
            minDate: getNextWeekday(currentDate), // Set the minimum date to the next weekday
            maxDate: "+1w", // Set the maximum date to one week from the selected date
            beforeShowDay: function (date) {
                // Disable weekends
                if (!isWeekday(date)) {
                    return [false];
                }
                return [true];
            }
        }).datepicker("setDate", "0");
        $(".datepicker").attr("readonly", true);
        $("#QuantityWantToLoan").on("keypress keyup blur", function (event) {
            // Allow only digits and backspace key (code 8)
            if (event.keyCode !== 8 && (event.keyCode < 48 || event.keyCode > 57)) {
                event.preventDefault();
            }
        });
    </script>
}

Views/LoanStock/Index.cshtml
@model IEnumerable<Group20_IoT.Models.ViewModel.LoanStockViewModel>
@{
    ViewBag.Title = "Loan Stock";
}
<style>
    .card-deck {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .card {
        width: 100% !important;
        margin-bottom: 1.7rem !important;
        background-color: #2E3842 !important;
        color: #fff !important; /* Change text color to white */
    }

    .card-header {
        background-color: #003366 !important;
        color: #fff !important; /* Change text color to white */
        text-align: center !important;
        padding: 0.75rem !important;
        font-weight: bold !important;
    }

    .card-body {
        padding: 1.25rem;
        text-align: center;
    }

    .badge {
        margin-right: 0.5rem;
        padding: 0.5em;
        border-radius: 4px;
        font-size: 14px;
    }

    .badge-success {
        background-color: #28a745;
        color: #fff;
    }

    .badge-danger {
        background-color: #dc3545;
        color: #fff;
    }

    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>
<br />
<div>
    <label>Enter Stock Name</label>
    <input type="text" id="searchInput" />
    <button id="searchButton" class="btn-primary">Search</button>
    <br />
    <button id="resetButton" class="btn-primary" style="display:none">Reset</button>
    <br />
    <select id="filterSortby">
        <option value="">Default Sorting</option>
        <option value="StockLow">Sort By Quantity: Low To High</option>
        <option value="StockHigh">Sort By Quantity: High To Low</option>
    </select>
</div>
<br />
<div>
    <label>Can&rsquo;t find what you&rsquo;re looking for? @Html.ActionLink("Request Stock", "Create", "RequestStock")</label>
</div>
<br />

<div id="loanStockTable">
    @Html.Partial("_LoanStockTable", Model as IEnumerable<Group20_IoT.Models.ViewModel.LoanStockViewModel>)
</div>


@section scripts {
    <script>
        $(document).ready(function () {
            var ResetButton = $("#resetButton");

            $("#searchButton").click(function () {
                var searchItem = $("#searchInput").val();

                $.ajax({
                    url: '@Url.Action("Search", "LoanStock")',
                    type: "GET",
                    data: { searchItem: searchItem },
                    success: function (data) {
                        $("#loanStockTable").html(data);
                        ResetButton.show();
                    },
                    error: function () {
                        notifyError("Error occurred while searching.");
                        ResetButton.show();
                    }
                });
            });

                ResetButton.click(function () {

        $.ajax({
            url: '@Url.Action("Reset", "LoanStock")',
            type: "GET",
            success: function (data) {
                $("#loanStockTable").html(data);
                ResetButton.hide();
            },
            error: function () {
                notifyError("Error occurred while resetting.");
                ResetButton.show();
            }
        });


});

            $("#filterSortby").change(function () {
                var sort = $(this).val();
                    $.ajax({
                    url: '@Url.Action("Sort", "LoanStock")',
                    type: "GET",
                        data: { sort: sort },
                    success: function (data) {
                        $("#loanStockTable").html(data);
                    },
                    error: function () {
                        notifyError("Error occurred while filtering.");
                    }
                });


            });
        });
    </script>
}

Views/LoanStock/_LoanStockTable.cshtml
@model IEnumerable<Group20_IoT.Models.ViewModel.LoanStockViewModel>

<div class="card-body">
    <div class="row">
        @foreach (var item in Model)
        {

            <div class="card">
                <div style="text-align:center"><img src="~/Content/Images/@item.ImageFile" class="card-img-top" alt="@item.ImageFile" style="max-height: 200px; max-width: 200px;"></div>
                <div class="card-body">
                    <h3 class="card-title"><strong>@Html.DisplayFor(modelItem => item.Name)</strong></h3>
                    <br />
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                    <p class="card-text"><strong>Stock Code:</strong> @Html.DisplayFor(modelItem => item.StockCode)</p>
                    @if (item.QuantityCanLoan == 0)
                    {
                        <p class="card-text">
                            <strong>Available Quantity To Loan:</strong> <strong style="color:red">Out Of Stock</strong>
                        </p>
                    }
                    else
                    {
                        <p class="card-text"><strong>Available Quantity To Loan:</strong> @Html.DisplayFor(modelItem => item.QuantityCanLoan)</p>
                    }

                    @if (item.QuantityCanLoan > 0)
                    {
                        @Html.ActionLink("Loan", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                    }
                </div>
            </div>

        }
    </div>
    </div>