Models/RequestStock.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Group20_IoT.Models
{
    public class RequestStock
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }

        // Created By
        [ForeignKey("Users")]
        public int UserId { get; set; }

        [Required(ErrorMessage = "Please enter the Stock Name")]
        [Display(Name = "Stock Name")]
        [StringLength(255,ErrorMessage = "The Stock Name must not exceed 255 characters")]
        public string StockName { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Please enter a valid Quantity")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "Please enter the Stock Price")]
        [Display(Name = "Stock Price")]
        [Range(0.05,double.MaxValue, ErrorMessage = "Please enter a valid Stock Price")]
        public double StockPrice { get; set; }

        [Required(ErrorMessage = "Please enter the link to the Stock")]
        [Display(Name = "Stock Link")]
        [StringLength(2000, ErrorMessage = "The Stock Link should not exceed 2000 characters")]
        [RegularExpression(@"^(https?://)?([\w-]+\.)+[\w-]+(/[\w- ./?%&=]*)?$", ErrorMessage = "Please enter a valid Stock Link")]
        public string StockLink { get; set; }

        public string StockImage { get; set; }
        [Display(Name = "Request Date")]
        public DateTime RequestDate { get; set; } = DateTime.Now;
        [Display(Name = "Approved")]
        public bool IsApproved { get; set; } = false;

        public virtual Users Users { get; set; }
    }
}

Models/ViewModel/RequestStockViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Group20_IoT.Models.ViewModel
{
    public class RequestStockViewModel
    {
        public int? Id { get; set; }
        public int UserId { get; set; }
        public string UniNum { get; set; }  
        public string UserName { get; set; }
        public string StockName { get; set; }
        public int Quantity { get; set; }
        public string StockPrice { get; set; }
        public string StockLink { get; set; }
        public string StockImage { get; set;}
        public string RequestDate { get; set; }
        public string Approved { get; set; }
        public string ApprovedBy { get; set; }
    }
}

Controllers/RequestStockController.cs
using Group20_IoT.Models;
using Group20_IoT.Models.ViewModel;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.Util;

namespace Group20_IoT.Controllers
{
    [SessionChecker("SuperAdmin","Admin","Member")]
    public class RequestStockController : Controller
    {
        private IoTContext db = new IoTContext();

        public List<RequestStockViewModel> getRequests(string search)
        {
            List<RequestStockViewModel> SortedRequests = new List<RequestStockViewModel>();

            if (search.IsNullOrEmpty())
            {
                SortedRequests = db.RequestStock.Include(x => x.Users)
                                .OrderByDescending(x => x.RequestDate)
                                .AsEnumerable()
                                .Select(x => new RequestStockViewModel
                                {
                                    Id = x.Id,
                                    UserId = x.UserId,
                                    UniNum = x.Users.UniNum,
                                    UserName = x.Users.GetFullName(),
                                    StockName = x.StockName,
                                    Quantity = x.Quantity,
                                    StockPrice = x.StockPrice.ToString("C"),
                                    StockLink = x.StockLink,
                                    StockImage = x.StockImage,
                                    RequestDate = x.RequestDate.ToString("yyyy/M/d"),
                                    Approved = x.IsApproved ? "Yes" : "No"
                                }).ToList();
            }
            else
            {
                SortedRequests = db.RequestStock.Include(x => x.Users)
                                .OrderByDescending(x => x.RequestDate)
                                .Where(x => x.StockName.ToLower().Contains(search.Trim().ToLower()))
                                .AsEnumerable()
                                .Select(x => new RequestStockViewModel
                                {
                                    Id = x.Id,
                                    UserId = x.UserId,
                                    UniNum = x.Users.UniNum,
                                    UserName = x.Users.GetFullName(),
                                    StockName = x.StockName,
                                    Quantity = x.Quantity,
                                    StockPrice = x.StockPrice.ToString("C"),
                                    StockLink = x.StockLink,
                                    StockImage = x.StockImage,
                                    RequestDate = x.RequestDate.ToString("yyyy/M/d"),
                                    Approved = x.IsApproved ? "Yes" : "No"
                                }).ToList();
            }

            return SortedRequests;
        }

        // GET: RequestStock
        public ActionResult Index()
        {
            return View(getRequests(null));
        }

        public ActionResult Search(string searchItem)
        {
            string UserType = Session["UserType"] as string;

            var SortedRequests = getRequests(searchItem);

            if(UserType != "Member") return PartialView("_RequestStockTableAdmin", SortedRequests);

            return PartialView("_RequestStockTable", SortedRequests);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RequestStock stock, HttpPostedFileBase image)
        {
            Users user = Session["User"] as Users;

            if (!stock.StockName.IsNullOrEmpty()) stock.StockName = stock.StockName.Trim();

            if (db.RequestStock.Any(r => r.StockName.ToLower() == stock.StockName.ToLower())) ModelState.AddModelError("StockName", "There is already a request with this Stock Name");

            if (image == null || image.ContentLength <= 0) ModelState.AddModelError("StockImage", "Please select an image");

            if (ModelState.IsValid)
            {
                string ImageGUID = Guid.NewGuid().ToString() + "_" + Path.GetFileName(image.FileName);
                string ImagePath = Path.Combine(Server.MapPath("~/Content/Request"), ImageGUID);

                image.SaveAs(ImagePath);

                stock.UserId = user.Id;
                stock.StockImage = ImageGUID;
                db.RequestStock.Add(stock);
                db.SaveChanges();

                _ = SharedMethods.SendEmail(user.GetFullName(), user.Email, "IoT System - Stock Request", $"Hello, {user.GetFullName()}.\n\nYour stock request:\n \"{stock.Quantity} x {stock.StockName}\" \nHas been submitted.\nYou will receive feedback about your stock request via email.\n\nThank you.\nKind Regards,\nIoT System.", false);

                return RedirectToAction(nameof(Index));
            }

            return View(stock);
        }

        public ActionResult MyRequestsOnly(bool showMyRequests)
        {
            Users user = Session["User"] as Users;

            List<RequestStockViewModel> SortedRequests = new List<RequestStockViewModel>();

            if (showMyRequests)
            {
                     SortedRequests = db.RequestStock.Include(x => x.Users)
                    .OrderByDescending(x => x.RequestDate)
                    .Where(x => x.UserId == user.Id)
                    .AsEnumerable()
                    .Select(x => new RequestStockViewModel
                    {
                        Id = x.Id,
                        UserId = x.UserId,
                        UniNum = x.Users.UniNum,
                        UserName = x.Users.GetFullName(),
                        StockName = x.StockName,
                        StockPrice = x.StockPrice.ToString("C"),
                        StockLink = x.StockLink,
                        StockImage = x.StockImage,
                        RequestDate = x.RequestDate.ToString("yyyy/M/d"),
                        Approved = x.IsApproved ? "Yes" : "No"
                    }).ToList();

            }
            else
            {
                SortedRequests = getRequests(null);
            }

            if (user.Role.Type != "Member") return PartialView("_RequestStockTableAdmin", SortedRequests);

            return PartialView("_RequestStockTable", SortedRequests);
        }


        [SessionChecker("SuperAdmin","Admin")]
        [HttpPost]
        public ActionResult AcceptStockRequest(int? id)
        {
            if (id == null) return RedirectToAction(nameof(Index));

            RequestStock stock = db.RequestStock.Find(id);

            if(stock == null) return RedirectToAction(nameof(Index));

            stock.IsApproved = true;

            db.Entry(stock).State = EntityState.Modified;
            db.SaveChanges();

            Users user = db.Users.Find(stock.UserId);

            _ = SharedMethods.SendEmail(user.GetFullName(), user.Email, "IoT System - Stock Request Accepted", $"Hello,{user.GetFullName()}.\n\nThe Stock you requested for,\n \"{stock.Quantity} x {stock.StockName}\" \n, has been accepted.\n\nThank you.\nKind regards,\nIoT System.", false);

            return Json(new { success = true, message = "Stock Request has been approved" });
        }
    }
}

Views/RequestStock/Create.cshtml
@model Group20_IoT.Models.RequestStock

@{
    ViewBag.Title = "Submit Stock Request";
}
<style>
    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>
<h2>Stock Request</h2>
<br />
@using (Html.BeginForm("Create", "RequestStock", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.StockName, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StockName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StockName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", min = 1, max = int.MaxValue } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockPrice, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StockPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StockPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockLink, htmlAttributes: new { @class = "control-label col-md-2 required-star" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StockLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StockLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="StockImage" class="control-label col-md-2 required-star">Stock Image</label>
            <div class="col-md-10">
                <input type="file" name="image" id="image" accept=".jpg, .jpeg, .png, .gif" />
                @Html.ValidationMessageFor(model => model.StockImage, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Request" class="btn-primary" />
            </div>
        </div>
    </div>

}
<br />
    <div>
        @Html.ActionLink("Back to List of Stock Requests", "Index", null, new { @class = "btn-primary" })
    </div>


@section scripts
{
    <script>

        $("#Quantity").on("keypress keyup blur", function (event) {
    // Allow only digits and backspace key (code 8)
    if (event.keyCode !== 8 && (event.keyCode < 48 || event.keyCode > 57)) {
    event.preventDefault();
    }
    });
    </script>

}

Views/RequestStock/Index.cshtml
@{
    Group20_IoT.Models.IoTContext db = new Group20_IoT.Models.IoTContext();
    ViewBag.Title = "Stock Request";
    Group20_IoT.Models.Users user = Session["User"] as Group20_IoT.Models.Users;
    int StandardRoleId = db.Role.Single(x => x.Type.Equals("Member")).Id;
}
<style>
    .card {
        width: 100% !important;
        margin-bottom: 1.7rem !important;
        background-color: #2E3842 !important;
        color: #fff !important; /* Change text color to white */
    }

    .card-header {
        background-color: #003366 !important;
        color: #fff !important; /* Change text color to white */
        text-align: center !important;
        padding: 0.75rem !important;
        font-weight: bold !important;
    }

    .card-body {
        padding: 1.25rem !important;
    }

    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        color: #03e9f4;
        font-size: 13px;
        text-decoration: none;
        text-transform: uppercase;
        border: none;
        outline: none;
        background: transparent;
        transition: background 0.5s, color 0.5s;
        margin-top: 20px;
        letter-spacing: 4px;
        cursor: pointer;
    }

        .btn-primary:hover {
            background: #03e9f4;
            color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0 100px #03e9f4;
        }
</style>
<h2>Stock Requests</h2>

<div>
    <label>Enter Requested Stock Name</label>
    <input type="text" id="searchInput" />
    <button id="searchButton" class="btn btn-primary">Search</button>
</div>
<br />
@if (user.RoleId == StandardRoleId)
{
    <div>
        <input type="checkbox" id="showMyRequests" /> Show My Requests Only
    </div>

    <div id="rsTable" class="card">
        @Html.Partial("_RequestStockTable", Model as List<Group20_IoT.Models.ViewModel.RequestStockViewModel>)
    </div>
}
else
{
    <div id="rsTable" class="card">
        @Html.Partial("_RequestStockTableAdmin", Model as List<Group20_IoT.Models.ViewModel.RequestStockViewModel>)
    </div>
}


@section scripts {
    <script>
        $(document).ready(function () {
            $("#searchButton").click(function () {
                var searchItem = $("#searchInput").val();

                $.ajax({
                    url: '@Url.Action("Search", "RequestStock")',
                    type: "GET",
                    data: { searchItem: searchItem },
                    success: function (data) {
                        $("#rsTable").html(data);
                    },
                    error: function () {
                        notifyError("Error occurred while searching.");
                    }
                });
            });
        });

        $("#showMyRequests").change(function () {
            var ShowMyRequests = this.checked;

            $.ajax({
                url: '@Url.Action("MyRequestsOnly", "RequestStock")',
                type: 'GET',
                data: { showMyRequests: ShowMyRequests },
                success: function (data) {
                    $("#rsTable").html(data);
                },
                error: function () {
                    notifyError("Error occurred while filtering.");
                }
            });
        });
    </script>
    <script>
      function AcceptStockReq(stockId)
      {
          $.ajax({
              url: '@Url.Action("AcceptStockRequest", "RequestStock")',
              type: 'POST',
              data: { id: stockId },
              dataType: 'json',
              success: function (data) {
                  if (!data.success) {
                      notifyError(data.message);
                  } else {
                      localStorage.setItem('notificationMessage', data.message);
                      location.reload();
                  }


              },
              error: function () {
                  notifyError("An error occurred while approving the Stock Request.");
              }
          });

  }
    </script>
}

Views/RequestStock/_RequestStockTable.cshtml
@model List<Group20_IoT.Models.ViewModel.RequestStockViewModel>


<table class="table text-white">
    <thead>
        <tr>
            <th>
                Reference #
            </th>
            <th>
                User
            </th>
            <th>
                Stock
            </th>
            <th>
                Quantity
            </th>
            <th>
                Price
            </th>
            <th>
                Link
            </th>
            <th>
                Date Requested
            </th>
            <th>
                Approved
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.UserName [@item.UniNum]
                    </td>
                    <td>
                        @item.StockName 
                    </td>
                    <td>
                        @item.Quantity
                    </td>
                    <td>
                        @item.StockPrice
                    </td>
                    <td>
                        <a href="@item.StockLink">Link</a>

                    </td>
                    <td>
                        @item.RequestDate
                    </td>
                    <td>
                        @item.Approved
                    </td>
                    <td>
                        <img src="~/Content/Request/@item.StockImage" alt="@item.StockImage" style="max-height:100px;max-width:100px" />
                    </td>

                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="7" style="text-align:center;font-size:16px"><strong>Sorry, no requested stock available</strong></td>
            </tr>
        }
    </tbody>
</table>

Views/RequestStock/_RequestStockTableAdmin.cshtml
@model List<Group20_IoT.Models.ViewModel.RequestStockViewModel>


<table class="table text-white">
    <tr>
        <th>
            Reference #
        </th>
        <th>
            User Requested
        </th>
        <th>
            Stock
        </th>
        <th>
            Quantity
        </th>
        <th>
            Price
        </th>
        <th>
            Link
        </th>
        <th>
            Date Requested
        </th>
        <th>
            Approved
        </th>
        <th></th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.UserName [@item.UniNum]
                </td>
                <td>
                    @item.StockName
                </td>
                <td>
                    @item.Quantity
                </td>
                <td>
                    @item.StockPrice
                </td>
                <td>
                    <a href="@item.StockLink">Link</a>

                </td>
                <td>
                    @item.RequestDate
                </td>
                <td>
                    @item.Approved
                </td>
                <td>
                    <img src="~/Content/Request/@item.StockImage" alt="@item.StockImage" style="max-height:100px;max-width:100px" />
                </td>
                <td>
                    @if (item.Approved == "No")
                    {
                    <button id="acceptButton" data-target="#AcceptModal-@item.Id" data-toggle="modal" class="btn-primary">Accept</button>
                    <div class="modal fade" data-keyboard="false" data-backdrop="static" id="AcceptModal-@item.Id" tabindex="-1">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content" style="background-color: #2E3842; color: #fff;">
                                <div class="modal-header">
                                    <input type="button" value="&#x274C;" class="close" data-dismiss="modal" />
                                    <p class="modal-title" style="color:white">Accept Stock Request</p>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to accept this stock request?</p>
                                </div>
                                <div class="modal-footer">
                                    <button id="confirmApproval" class="btn btn-primary" onclick="AcceptStockReq(@item.Id)" data-dismiss="modal">Yes</button>
                                    <button class="btn btn-secondary" id="Close-@item.Id" data-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    } 
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="7" style="text-align:center;font-size:16px"><strong>Sorry, no requested stock available</strong></td>
        </tr>
    }
</table>